import { FC, ReactNode } from "react";
import Head from "next/head";
import { NavBar } from "../nav-bar";
import styles from "./main-layout.module.css";

export const MainLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main className={styles.main}>{children}</main>
    </div>
  );
};
